name: CI Workflow

on:
  push:
    branches:
      - main  # Укажите нужные ветки для запуска

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.5-alpine
        env:
          POSTGRES_DB: gitlocalize-editor_test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
        ports:
          - 5432:5432
      elasticsearch:
        image: blacktop/elasticsearch:7.10
        ports:
          - 9200:9200

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Укажите вашу версию Ruby
          bundler-cache: true  # Автоматическое кеширование используемых gem'ов

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14  # Укажите вашу версию Node.js
          cache: 'yarn'  # Автоматическое кеширование зависимостей Yarn

      - name: Install Node dependencies
        run: |
          #yarn install
          echo "yarn install"

      - name: Run Rubocop
        run: |
          #bundle exec rubocop
          echo "bundle exec rubocop"

      - name: Set up database
        run: |
          echo "bundle exec rake db:create"
          #bundle exec rake db:create
          #bundle exec rake db:test:prepare

      - name: Run tests
        env:
          DATABASE_PASSWORD: password
          DATABASE_USERNAME: user
          RAILS_ENV: test
          TEST_DATABASE_HOST: localhost
          ELASTICSEARCH_URL: http://localhost:9200
          GOOGLE_PROJECT: gitlocalize
        run: |
          #pip3 install -r requirements.txt
          #bundle exec rake spec
          echo "install python dependencies and rake"

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}  # Задайте в секретах вашего репозитория
